# Generated by `just bump-formula`. Do not edit by hand; copy to the asteroidpm/homebrew-ender tap.
class EnderPayablesMcp < Formula
  desc "Ender public MCP server for creating payables (invoices) via the Ender API"
  homepage "https://docs.ender.com/customer-guides/public-api/mcp-server"
  version "0.1.0"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://dl.ender.com/ender-payables-mcp/0.1.0/ender-payables-mcp-0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "fab319999c55b5ce6b6d20b464dc468ae11ccf114519aceeafa0db2c2aae96ce"
    end
    on_intel do
      url "https://dl.ender.com/ender-payables-mcp/0.1.0/ender-payables-mcp-0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "24e5505ba2f8f1407f76aaedcec75bc4d3485f0a4206313f3e7bdf9403bec86d"
    end
  end

  on_linux do
    on_arm do
      url "https://dl.ender.com/ender-payables-mcp/0.1.0/ender-payables-mcp-0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "514edef90fc6b723ceb95644f967461d950d03ddf74269168195affd9159dc3a"
    end
    on_intel do
      url "https://dl.ender.com/ender-payables-mcp/0.1.0/ender-payables-mcp-0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "647a52fba95025a5a54f6b001a67c30863ef2a72fa7e542b10226a83c4bb776a"
    end
  end

  def install
    bin.install "ender-payables-mcp-server"
  end

  test do
    assert_match "ender-payables-mcp-server", shell_output("#{bin}/ender-payables-mcp-server --help 2>&1", 2)
  end
end
